language: c++
sudo: required
dist: trusty

matrix:
  include:
    # Linux GCC Builds
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - binutils
      env:
        - C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE='Release' SANITIZER="" ADDITIONAL_FLAGS="-fuse-ld=gold"
        - C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE='Debug' SANITIZER="" ADDITIONAL_FLAGS="-fuse-ld=gold"
        - C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE='Coverage' SANITIZER="" ADDITIONAL_FLAGS="-fuse-ld=gold"
        - C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE='Debug' SANITIZER="address" ADDITIONAL_FLAGS="-fuse-ld=gold"
        #- C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE='Debug' SANITIZER="thread" ADDITIONAL_FLAGS="-fuse-ld=gold" # Libtsan is missing
        - C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BUILD_TYPE='Debug' SANITIZER="undefined" ADDITIONAL_FLAGS="-fuse-ld=gold"
 
    # Linux Clang Builds
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - g++-5
            - clang-3.8
            - binutils
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE='Release' SANITIZER="" ADDITIONAL_FLAGS="-fuse-ld=gold"
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE='Debug' SANITIZER="" ADDITIONAL_FLAGS="-fuse-ld=gold"
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE='Debug' SANITIZER="address" ADDITIONAL_FLAGS="-fuse-ld=gold"
        #- C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE='Debug' SANITIZER="memory" ADDITIONAL_FLAGS="-fuse-ld=gold" # Disabled for now because of false positive and failing blacklist
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE='Debug' SANITIZER="thread" ADDITIONAL_FLAGS="-fuse-ld=gold"
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BUILD_TYPE='Debug' SANITIZER="undefined" ADDITIONAL_FLAGS="-fuse-ld=gold"

    # OSX Clang Builds
    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - C_COMPILER=clang CXX_COMPILER='clang++' BUILD_TYPE='Release' SANITIZER="" ADDITIONAL_FLAGS=""
        - C_COMPILER=clang CXX_COMPILER='clang++' BUILD_TYPE='Debug' SANITIZER="" ADDITIONAL_FLAGS=""
        - C_COMPILER=clang CXX_COMPILER='clang++' BUILD_TYPE='Debug' SANITIZER="address" ADDITIONAL_FLAGS=""
        #- C_COMPILER=clang CXX_COMPILER='clang++' BUILD_TYPE='Debug' SANITIZER="memory" ADDITIONAL_FLAGS="" # Currently unsupported
        - C_COMPILER=clang CXX_COMPILER='clang++' BUILD_TYPE='Debug' SANITIZER="thread" ADDITIONAL_FLAGS=""
        #- C_COMPILER=clang CXX_COMPILER='clang++' BUILD_TYPE='Debug' SANITIZER="undefined" ADDITIONAL_FLAGS="" # Fails at link

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo "Nothin"
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      # Seems already installed now
      # brew install cmake
      cmake --version
    fi

before_script:
  - export CC=${C_COMPILER}
  - export CXX=${CXX_COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p Build
  - cd Build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="${ADDITIONAL_FLAGS}" -DPROJECT_BUILD_SANITIZER_TYPE=${SANITIZER}

script:
  - make -j2
  - ctest -V
  - ./bin/runcppproject

after_success:
  - |
    if [[ "${BUILD_TYPE}" == "Coverage" ]]; then
      bash <(curl -s https://codecov.io/bash)
    fi
