language: cpp
compiler:
  - clang
  - gcc

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -Hprojects/CMake -BBuild -DCMAKE_BUILD_TYPE=Release
  - cd Build

script:
  - make -j2
  - ctest -V -j2

