environment:
  matrix:
  - config: Debug
  - config: RelWithDebInfo

shallow_clone: true

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\cppproject

platform: x64

install:
  - set
  - echo cmake on AppVeyor
  - cmake -version
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - cd c:\projects\cppproject
  - mkdir build
  - cd build
  - echo %config%
  # This will produce lots of LNK4099 warnings which can be ignored.
  # Unfortunately they can't be disabled, see
  # http://stackoverflow.com/questions/661606/visual-c-how-to-disable-specific-linker-warnings
  - cmake -LA -G "Visual Studio 14 Win64"
    -DCMAKE_BUILD_TYPE=%config%
    ..
  - msbuild cppproject.sln /p:Configuration=%config% /toolsversion:14.0 /p:Platform=x64 /p:PlatformToolset=v140
  #- cmake .. -LA -G "NMake Makefiles"
    #-DCMAKE_BUILD_TYPE=%config%
  #- nmake

test_script:
  # "-E testdata-overview" exempts one test we know fails on Appveyor
  #    because we currently don't have spatialite support.
  - ctest --output-on-failure
    -C %config%
    -E testdata-overview
